

SUPABASE_URL = "https://xptclaptslnectnpsvnx.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwdGNsYXB0c2xuZWN0bnBzdm54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMTA5NDQsImV4cCI6MjA2NDg4Njk0NH0.YWDbWJKIZLaduFpl-VsbpvSFemYJzgrj1OPrxxVAJ68"

EMAIL = "saisandeep2606@gmail.com"
EMAIL_PASSWORD = "aabp spen ynck ggth"
